- name: install nginx and start
  hosts: local
  become: yes 
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: restart
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
    