- name: variables to print 
  hosts: local
  connection: local
  vars:
    course: "devops"
    duration: "120hrs" 
    trainer: "siva"
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "hi,i am learning {{course}},{{duration}},{{trainer}}"
  
  